//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string PersonalNum { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public decimal TotalDebt { get; set; }
        public string Note { get; set; }
    }
}
