//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CustomerManagementEntities : DbContext
    {
        public CustomerManagementEntities()
            : base("name=CustomerManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMUser> CMUser { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
    
        public virtual int usp_AddCMUser(string pUserName, string pUserPassword)
        {
            var pUserNameParameter = pUserName != null ?
                new ObjectParameter("pUserName", pUserName) :
                new ObjectParameter("pUserName", typeof(string));
    
            var pUserPasswordParameter = pUserPassword != null ?
                new ObjectParameter("pUserPassword", pUserPassword) :
                new ObjectParameter("pUserPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AddCMUser", pUserNameParameter, pUserPasswordParameter);
        }
    
        public virtual int usp_AddCustomer(string pPersonalNum, string pName, string pLastName, Nullable<decimal> pTotalDebt, string pNote)
        {
            var pPersonalNumParameter = pPersonalNum != null ?
                new ObjectParameter("pPersonalNum", pPersonalNum) :
                new ObjectParameter("pPersonalNum", typeof(string));
    
            var pNameParameter = pName != null ?
                new ObjectParameter("pName", pName) :
                new ObjectParameter("pName", typeof(string));
    
            var pLastNameParameter = pLastName != null ?
                new ObjectParameter("pLastName", pLastName) :
                new ObjectParameter("pLastName", typeof(string));
    
            var pTotalDebtParameter = pTotalDebt.HasValue ?
                new ObjectParameter("pTotalDebt", pTotalDebt) :
                new ObjectParameter("pTotalDebt", typeof(decimal));
    
            var pNoteParameter = pNote != null ?
                new ObjectParameter("pNote", pNote) :
                new ObjectParameter("pNote", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AddCustomer", pPersonalNumParameter, pNameParameter, pLastNameParameter, pTotalDebtParameter, pNoteParameter);
        }
    
        public virtual ObjectResult<usp_AllCustomers_Result> usp_AllCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AllCustomers_Result>("usp_AllCustomers");
        }
    
        public virtual int usp_CMLogin(string pUserName, string pUserPassword, ObjectParameter pResult)
        {
            var pUserNameParameter = pUserName != null ?
                new ObjectParameter("pUserName", pUserName) :
                new ObjectParameter("pUserName", typeof(string));
    
            var pUserPasswordParameter = pUserPassword != null ?
                new ObjectParameter("pUserPassword", pUserPassword) :
                new ObjectParameter("pUserPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CMLogin", pUserNameParameter, pUserPasswordParameter, pResult);
        }
    
        public virtual int usp_DeleteCustomer(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteCustomer", iDParameter);
        }
    
        public virtual int usp_UpdateCustomer(Nullable<int> iD, string pPersonalNum, string pName, string pLastName, Nullable<decimal> pTotalDebt, string pNote)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var pPersonalNumParameter = pPersonalNum != null ?
                new ObjectParameter("pPersonalNum", pPersonalNum) :
                new ObjectParameter("pPersonalNum", typeof(string));
    
            var pNameParameter = pName != null ?
                new ObjectParameter("pName", pName) :
                new ObjectParameter("pName", typeof(string));
    
            var pLastNameParameter = pLastName != null ?
                new ObjectParameter("pLastName", pLastName) :
                new ObjectParameter("pLastName", typeof(string));
    
            var pTotalDebtParameter = pTotalDebt.HasValue ?
                new ObjectParameter("pTotalDebt", pTotalDebt) :
                new ObjectParameter("pTotalDebt", typeof(decimal));
    
            var pNoteParameter = pNote != null ?
                new ObjectParameter("pNote", pNote) :
                new ObjectParameter("pNote", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateCustomer", iDParameter, pPersonalNumParameter, pNameParameter, pLastNameParameter, pTotalDebtParameter, pNoteParameter);
        }
    }
}
